name: ci-flow

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os.imageName }}
    strategy:
      matrix:
        rust_toolchain: ["stable"]
        os:
          - imageName: "ubuntu-latest"
            target: x86_64-unknown-linux-gnu
            profile: linux
          - imageName: "macOS-latest"
            target: x86_64-apple-darwin
            profile: mac
          - imageName: "windows-2019"
            target: x86_64-pc-windows-msvc
            profile: windows
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_toolchain }}
          override: true
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v4.1.1
      - name: Run tests
        run: cargo make --disable-check-for-updates --profile ${{ matrix.os.profile }} --env TARGET=${{matrix.os.target}} ci-flow
